// generated by scripts/generate-operations-map.mjs
export const operationIdToPath = {
  "basic.getTransactionsByIds": {
    "path": "/batch/transactions",
    "method": "GET"
  },
  "basic.getCharge": {
    "path": "/charge",
    "method": "GET"
  },
  "client.getSupportedRegistrationCountries": {
    "path": "/client/supported_registration_countries",
    "method": "GET"
  },
  "basic_client.getTransactions": {
    "path": "/clients/{client_id}/transactions",
    "method": "POST"
  },
  "basic_client.getTransaction": {
    "path": "/clients/{client_id}/transactions/{transaction_id}",
    "method": "GET"
  },
  "users.createGuestUser": {
    "path": "/guest_users",
    "method": "POST"
  },
  "personal.getAccountSession": {
    "path": "/me/account_session",
    "method": "GET"
  },
  "users.getBalances": {
    "path": "/me/balances",
    "method": "GET"
  },
  "basic.getCarrierFacilityOptions": {
    "path": "/me/carriers/{carrier_id}/facilities",
    "method": "GET"
  },
  "personal.getDebitAccount": {
    "path": "/me/debit_account",
    "method": "GET"
  },
  "personal.setDebitAccount": {
    "path": "/me/debit_account",
    "method": "POST"
  },
  "users.getUserFeatures": {
    "path": "/me/features",
    "method": "GET"
  },
  "users.setInstantPayouts": {
    "path": "/me/features/instant_payouts",
    "method": "POST"
  },
  "personal.getInstantPayoutBalance": {
    "path": "/me/instant_payout_balance",
    "method": "GET"
  },
  "basic.createMultiUseListing": {
    "path": "/me/multi_use_listings/create",
    "method": "POST"
  },
  "app_notifs.getNotifications": {
    "path": "/me/notifications",
    "method": "GET"
  },
  "personal.getPayoutAttempts": {
    "path": "/me/payout_attempts",
    "method": "GET"
  },
  "getAdditionalIdentityDocumentVerificationStatus": {
    "path": "/me/personal/additional_identity_document/verification_status",
    "method": "GET"
  },
  "getAdditionalIdentityDocumentBackVerificationStatus": {
    "path": "/me/personal/additional_identity_document_back/verification_status",
    "method": "GET"
  },
  "personal.getDetails": {
    "path": "/me/personal/details",
    "method": "GET"
  },
  "personal.setDetails": {
    "path": "/me/personal/details",
    "method": "PATCH"
  },
  "getIdentityDocumentVerificationStatus": {
    "path": "/me/personal/identity_document/verification_status",
    "method": "GET"
  },
  "getIdentityDocumentBackVerificationStatus": {
    "path": "/me/personal/identity_document_back/verification_status",
    "method": "GET"
  },
  "getStripePublishableKeyForUser": {
    "path": "/me/personal/stripe_publishable_key",
    "method": "GET"
  },
  "getProfilePayoutStatus": {
    "path": "/me/profile/payout_status",
    "method": "GET"
  },
  "basic.createSingleUseListing": {
    "path": "/me/single_use_listings/create",
    "method": "POST"
  },
  "personal.addStripeFinancialConnectionsAccount": {
    "path": "/me/stripe_financial_connections/add_account",
    "method": "POST"
  },
  "personal.getStripeFinancialConnectionsOwnership": {
    "path": "/me/stripe_financial_connections/ownership",
    "method": "GET"
  },
  "personal.prepareStripeFinancialConnectionsAccount": {
    "path": "/me/stripe_financial_connections/prepare_account",
    "method": "POST"
  },
  "basic.getTransactions": {
    "path": "/transactions",
    "method": "GET"
  },
  "basic.createTransaction": {
    "path": "/transactions",
    "method": "POST"
  },
  "basic.createAndJoinTransaction": {
    "path": "/me/transactions/create_and_join",
    "method": "POST"
  },
  "basic.createTransactionWithGuestUser": {
    "path": "/me/transactions/create_with_guest_user",
    "method": "POST"
  },
  "personal.getVerificationMethod": {
    "path": "/me/verification_method",
    "method": "GET"
  },
  "personal.getVerificationSession": {
    "path": "/me/verification_session",
    "method": "GET"
  },
  "personal.getVerificationSessionNative": {
    "path": "/me/verification_session_native",
    "method": "GET"
  },
  "personal.getVerificationStatus": {
    "path": "/me/verification_status",
    "method": "GET"
  },
  "basic.deleteMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}",
    "method": "DELETE"
  },
  "basic.getMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}",
    "method": "GET"
  },
  "basic.updateMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}",
    "method": "PATCH"
  },
  "basic.createTransactionFromMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}/create_transaction",
    "method": "POST"
  },
  "basic.createTransactionWithGuestBuyerFromMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}/create_transaction_with_guest_buyer",
    "method": "POST"
  },
  "basic.disableMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}/disable",
    "method": "POST"
  },
  "basic.enableMultiUseListing": {
    "path": "/multi_use_listings/{listing_id}/enable",
    "method": "POST"
  },
  "basic.setMultiUseListingDescription": {
    "path": "/multi_use_listings/{listing_id}/set_description",
    "method": "POST"
  },
  "basic.setMultiUseListingPricing": {
    "path": "/multi_use_listings/{listing_id}/set_pricing",
    "method": "POST"
  },
  "app_notifs.getNotification": {
    "path": "/notifications/{notification_id}",
    "method": "GET"
  },
  "app_notifs.markNotificationAsRead": {
    "path": "/notifications/{notification_id}/mark_as_read",
    "method": "POST"
  },
  "getP2pTransactionsByIds": {
    "path": "/p2p/batch/transactions",
    "method": "GET"
  },
  "p2p.getCharge": {
    "path": "/p2p/charge",
    "method": "GET"
  },
  "p2p_client.getTransactions": {
    "path": "/p2p/clients/{client_id}/transactions",
    "method": "POST"
  },
  "p2p_client.getTransaction": {
    "path": "/p2p/clients/{client_id}/transactions/{transaction_id}",
    "method": "GET"
  },
  "p2p.createWithSeller": {
    "path": "/p2p/listings/create_with_seller",
    "method": "POST"
  },
  "createP2PMultiUseListingWithDetails": {
    "path": "/p2p/me/multi_use_listings/create",
    "method": "POST"
  },
  "createP2PSingleUseListingWithDetails": {
    "path": "/p2p/me/single_use_listings/create",
    "method": "POST"
  },
  "p2p.getTransactions": {
    "path": "/p2p/me/transactions",
    "method": "GET"
  },
  "p2p.createTransaction": {
    "path": "/p2p/me/transactions",
    "method": "POST"
  },
  "p2p.createAndJoinTransaction": {
    "path": "/p2p/me/transactions/create_and_join",
    "method": "POST"
  },
  "p2p.createTransactionWithGuestUser": {
    "path": "/p2p/me/transactions/create_with_guest_user",
    "method": "POST"
  },
  "deleteP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}",
    "method": "DELETE"
  },
  "getP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}",
    "method": "GET"
  },
  "patchP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}",
    "method": "PATCH"
  },
  "createTransactionFromP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}/create_transaction",
    "method": "POST"
  },
  "disableP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}/disable",
    "method": "POST"
  },
  "enableP2PMultiUseListing": {
    "path": "/p2p/multi_use_listings/{listingId}/enable",
    "method": "POST"
  },
  "setP2PMultiUseListingPricing": {
    "path": "/p2p/multi_use_listings/{listingId}/set_deposit_pricing",
    "method": "POST"
  },
  "setP2PMultiUseListingDescription": {
    "path": "/p2p/multi_use_listings/{listingId}/set_description",
    "method": "POST"
  },
  "setP2PMultiUseListingSkipRemainder": {
    "path": "/p2p/multi_use_listings/{listingId}/set_skip_remainder",
    "method": "POST"
  },
  "deleteP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}",
    "method": "DELETE"
  },
  "getP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}",
    "method": "GET"
  },
  "patchP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}",
    "method": "PATCH"
  },
  "createTransactionFromP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}/create_transaction",
    "method": "POST"
  },
  "disableP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}/disable",
    "method": "POST"
  },
  "enableP2PSingleUseListing": {
    "path": "/p2p/single_use_listings/{listingId}/enable",
    "method": "POST"
  },
  "setP2PSingleUseListingPricing": {
    "path": "/p2p/single_use_listings/{listingId}/set_deposit_pricing",
    "method": "POST"
  },
  "setP2PSingleUseListingDescription": {
    "path": "/p2p/single_use_listings/{listingId}/set_description",
    "method": "POST"
  },
  "p2p.getTransaction": {
    "path": "/p2p/transactions/{transaction_id}",
    "method": "GET"
  },
  "updateF2fTransaction": {
    "path": "/p2p/transactions/{transaction_id}",
    "method": "PATCH"
  },
  "p2p.acceptComplaint": {
    "path": "/p2p/transactions/{transaction_id}/accept_complaint",
    "method": "POST"
  },
  "p2p.acceptDeposit": {
    "path": "/p2p/transactions/{transaction_id}/accept_deposit",
    "method": "POST"
  },
  "p2p.acceptDepositWithGuestSeller": {
    "path": "/p2p/transactions/{transaction_id}/accept_deposit_with_guest_seller",
    "method": "POST"
  },
  "p2p.getBankTransferDetails": {
    "path": "/p2p/transactions/{transaction_id}/bank_transfer_details",
    "method": "GET"
  },
  "p2p.getBillingDetails": {
    "path": "/p2p/transactions/{transaction_id}/billing_details",
    "method": "GET"
  },
  "p2p.cancelWithDescription": {
    "path": "/p2p/transactions/{transaction_id}/cancel_with_description",
    "method": "POST"
  },
  "p2p.cancelP2PTransactionWithDescriptionAsGuest": {
    "path": "/p2p/transactions/{transaction_id}/cancel_with_description_with_guest_user",
    "method": "POST"
  },
  "p2p.claimForBuyer": {
    "path": "/p2p/transactions/{transaction_id}/claim_for_buyer",
    "method": "POST"
  },
  "p2p.claimTransactionForSeller": {
    "path": "/p2p/transactions/{transaction_id}/claim_for_seller",
    "method": "POST"
  },
  "p2p.submitComplaint": {
    "path": "/p2p/transactions/{transaction_id}/complain",
    "method": "POST"
  },
  "p2p.submitComplaintWithGuestBuyer": {
    "path": "/p2p/transactions/{transaction_id}/complain_with_guest_buyer",
    "method": "POST"
  },
  "p2p.confirmHandover": {
    "path": "/p2p/transactions/{transaction_id}/confirm_handover",
    "method": "POST"
  },
  "p2p.confirmHandoverWithGuestUserForTransaction": {
    "path": "/p2p/transactions/{transaction_id}/confirm_handover_with_guest_user",
    "method": "POST"
  },
  "p2p.getDepositStripeClientSecretForTransaction": {
    "path": "/p2p/transactions/{transaction_id}/deposit_stripe_client_secret",
    "method": "GET"
  },
  "p2p.endComplaintPeriodWithGuestBuyer": {
    "path": "/p2p/transactions/{transaction_id}/end_complaint_period_with_guest_buyer",
    "method": "POST"
  },
  "p2p.joinWithGuest": {
    "path": "/p2p/transactions/{transaction_id}/join_with_guest",
    "method": "POST"
  },
  "p2p.getTransactionMetadata": {
    "path": "/p2p/transactions/{transaction_id}/metadata",
    "method": "GET"
  },
  "p2p.setTransactionMetadata": {
    "path": "/p2p/transactions/{transaction_id}/metadata",
    "method": "POST"
  },
  "p2p.getRemainderStripeClientSecretForTransaction": {
    "path": "/p2p/transactions/{transaction_id}/remainder_stripe_client_secret",
    "method": "GET"
  },
  "p2p.setDepositPaymentMethod": {
    "path": "/p2p/transactions/{transaction_id}/set_deposit_payment_method",
    "method": "POST"
  },
  "p2p.getStripePublishableKeyForTransaction": {
    "path": "/p2p/transactions/{transaction_id}/stripe_publishable_key",
    "method": "GET"
  },
  "getBuyerDetailsFromP2PTransaction": {
    "path": "/p2p/transactions/{transactionId}/buyer_details",
    "method": "GET"
  },
  "getSellerDetailsFromP2PTransaction": {
    "path": "/p2p/transactions/{transactionId}/seller_details",
    "method": "GET"
  },
  "setPriceForP2PTransaction": {
    "path": "/p2p/transactions/{transactionId}/set_price",
    "method": "POST"
  },
  "skipRemainderForP2PTransaction": {
    "path": "/p2p/transactions/{transactionId}/skip_remainder",
    "method": "POST"
  },
  "p2p.claimAsBuyer": {
    "path": "/p2p/transactions_by_claim_secret/{secret}/claim_as_buyer",
    "method": "POST"
  },
  "p2p.claimTransactionAsSeller": {
    "path": "/p2p/transactions_by_claim_secret/{secret}/claim_as_seller",
    "method": "POST"
  },
  "p2p.joinTransactionByJoinCode": {
    "path": "/p2p/transactions_by_join_code/{join_code}/join",
    "method": "POST"
  },
  "p2p.rejectTransactionByJoinCode": {
    "path": "/p2p/transactions_by_join_code/{join_code}/reject",
    "method": "POST"
  },
  "getP2PTransactionByJoinCode": {
    "path": "/p2p/transactions_by_join_code/{joinCode}",
    "method": "GET"
  },
  "basic.getShippoShippingRates": {
    "path": "/shippo_shipping_rates",
    "method": "POST"
  },
  "basic.deleteSingleUseListing": {
    "path": "/single_use_listings/{listing_id}",
    "method": "DELETE"
  },
  "basic.getSingleUseListing": {
    "path": "/single_use_listings/{listing_id}",
    "method": "GET"
  },
  "basic.updateSingleUseListing": {
    "path": "/single_use_listings/{listing_id}",
    "method": "PATCH"
  },
  "basic.createTransactionFromSingleUseListing": {
    "path": "/single_use_listings/{listing_id}/create_transaction",
    "method": "POST"
  },
  "basic.createTransactionWithGuestBuyerFromSingleUseListing": {
    "path": "/single_use_listings/{listing_id}/create_transaction_with_guest_buyer",
    "method": "POST"
  },
  "basic.disableSingleUseListing": {
    "path": "/single_use_listings/{listing_id}/disable",
    "method": "POST"
  },
  "basic.enableSingleUseListing": {
    "path": "/single_use_listings/{listing_id}/enable",
    "method": "POST"
  },
  "basic.setSingleUseListingDescription": {
    "path": "/single_use_listings/{listing_id}/set_description",
    "method": "POST"
  },
  "basic.setSingleUseListingPricing": {
    "path": "/single_use_listings/{listing_id}/set_pricing",
    "method": "POST"
  },
  "getSupportedCarriers": {
    "path": "/supported_carriers",
    "method": "GET"
  },
  "basic.getTransactionByJoinCode": {
    "path": "/transactions",
    "method": "GET"
  },
  "basic.joinTransaction": {
    "path": "/transactions",
    "method": "PUT"
  },
  "basic.rejectTransactionByJoinCode": {
    "path": "/transactions-by-join-code/{join_code}/reject",
    "method": "POST"
  },
  "basic.getTransaction": {
    "path": "/transactions/{transaction_id}",
    "method": "GET"
  },
  "updateTransaction": {
    "path": "/transactions/{transaction_id}",
    "method": "PATCH"
  },
  "basic.acceptComplaint": {
    "path": "/transactions/{transaction_id}/accept_complaint",
    "method": "POST"
  },
  "basic.acceptListingTransaction": {
    "path": "/transactions/{transaction_id}/accept_listing_transaction",
    "method": "POST"
  },
  "basic.acceptPayment": {
    "path": "/transactions/{transaction_id}/accept_payment",
    "method": "POST"
  },
  "basic.acceptPaymentWithGuestSeller": {
    "path": "/transactions/{transaction_id}/accept_payment_with_guest_seller",
    "method": "POST"
  },
  "basic.getBankTransferDetails": {
    "path": "/transactions/{transaction_id}/bank_transfer_details",
    "method": "GET"
  },
  "basic.getBillingDetails": {
    "path": "/transactions/{transaction_id}/billing_details",
    "method": "GET"
  },
  "basic.getBuyerDetails": {
    "path": "/transactions/{transaction_id}/buyer_details",
    "method": "GET"
  },
  "basic.cancelTransaction": {
    "path": "/transactions/{transaction_id}/cancel",
    "method": "POST"
  },
  "basic.cancelTransactionWithGuestUser": {
    "path": "/transactions/{transaction_id}/cancel_with_guest_user",
    "method": "POST"
  },
  "basic.getChargeForTransaction": {
    "path": "/transactions/{transaction_id}/charge",
    "method": "GET"
  },
  "basic.claimTransactionForBuyer": {
    "path": "/transactions/{transaction_id}/claim_for_buyer",
    "method": "POST"
  },
  "basic.claimTransactionForSeller": {
    "path": "/transactions/{transaction_id}/claim_for_seller",
    "method": "POST"
  },
  "basic.submitComplaintWithDescription": {
    "path": "/transactions/{transaction_id}/complain_with_description",
    "method": "POST"
  },
  "basic.submitComplaintWithGuestBuyer": {
    "path": "/transactions/{transaction_id}/complain_with_guest_buyer",
    "method": "POST"
  },
  "basic.confirmDelivery": {
    "path": "/transactions/{transaction_id}/confirm_delivery",
    "method": "POST"
  },
  "basic.confirmDeliveryWithGuestBuyer": {
    "path": "/transactions/{transaction_id}/confirm_delivery_with_guest_buyer",
    "method": "POST"
  },
  "basic.setDeliveryPoint": {
    "path": "/transactions/{transaction_id}/delivery_point",
    "method": "POST"
  },
  "basic.endComplaintPeriod": {
    "path": "/transactions/{transaction_id}/end_complaint_period",
    "method": "POST"
  },
  "basic.extendTrackingDeadlineForTransaction": {
    "path": "/transactions/{transaction_id}/extend_tracking_deadline",
    "method": "POST"
  },
  "basic.generateShipmentLabel": {
    "path": "/transactions/{transaction_id}/generate_shipment_label",
    "method": "POST"
  },
  "basic.setPickUpPoint": {
    "path": "/transactions/{transaction_id}/pick_up_point",
    "method": "POST"
  },
  "basic.rejectListingTransaction": {
    "path": "/transactions/{transaction_id}/reject_listing_transaction",
    "method": "POST"
  },
  "basic.getSellerDetails": {
    "path": "/transactions/{transaction_id}/seller_details",
    "method": "GET"
  },
  "basic.setPaymentMethodForTransaction": {
    "path": "/transactions/{transaction_id}/set_payment_method",
    "method": "POST"
  },
  "basic.getShippingDetailsFromTransaction": {
    "path": "/transactions/{transaction_id}/shipping_details",
    "method": "GET"
  },
  "basic.setShippingDetails": {
    "path": "/transactions/{transaction_id}/shipping_details",
    "method": "POST"
  },
  "basic.setShippoAddress": {
    "path": "/transactions/{transaction_id}/shippo_address",
    "method": "POST"
  },
  "basic.setShippoCustomsDeclaration": {
    "path": "/transactions/{transaction_id}/shippo_customs_declaration",
    "method": "POST"
  },
  "basic.setShippoParcelDetails": {
    "path": "/transactions/{transaction_id}/shippo_parcel_details",
    "method": "POST"
  },
  "basic.getShippoShippingLabel": {
    "path": "/transactions/{transaction_id}/shippo_shipping_label",
    "method": "GET"
  },
  "basic.setShippoShippingRate": {
    "path": "/transactions/{transaction_id}/shippo_shipping_rate",
    "method": "POST"
  },
  "basic.getShippoShippingRatesForTransaction": {
    "path": "/transactions/{transaction_id}/shippo_shipping_rates",
    "method": "GET"
  },
  "getStripeClientSecretForTransaction": {
    "path": "/transactions/{transaction_id}/stripe_client_secret",
    "method": "GET"
  },
  "basic.getStripePublishableKeyForTransaction": {
    "path": "/transactions/{transaction_id}/stripe_publishable_key",
    "method": "GET"
  },
  "basic.submitOrderIssue": {
    "path": "/transactions/{transaction_id}/submit_order_issue",
    "method": "POST"
  },
  "basic.trackTransaction": {
    "path": "/transactions/{transaction_id}/track",
    "method": "POST"
  },
  "basic.trackTransactionWithGuestSeller": {
    "path": "/transactions/{transaction_id}/track_with_guest_seller",
    "method": "POST"
  },
  "basic.claimAsBuyer": {
    "path": "/transactions_by_claim_secret/{secret}/claim_as_buyer",
    "method": "POST"
  },
  "basic.claimTransactionAsSeller": {
    "path": "/transactions_by_claim_secret/{secret}/claim_as_seller",
    "method": "POST"
  },
  "users_client.getUserByClientID": {
    "path": "/users/clients/{client_id}/users/{user_id}",
    "method": "GET"
  },
  "oauth.getUser": {
    "path": "/users/{userId}",
    "method": "GET"
  },
  "oauth.updateUser": {
    "path": "/users/{userId}",
    "method": "PUT"
  }
} as const;
