// generated by scripts/generate-security-map.mjs
export const securityMap = {
  "/batch/transactions": {
    "GET": [
      "OAuth2"
    ]
  },
  "/charge": {
    "GET": [
      "OAuth2",
      "APIKey"
    ]
  },
  "/client/supported_registration_countries": {
    "GET": [
      "OAuth2"
    ]
  },
  "/guest_users": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/account_session": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/balances": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/carriers/{carrier_id}/facilities": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/debit_account": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ]
  },
  "/me/features": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/features/instant_payouts": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/instant_payout_balance": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/multi_use_listings/create": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/notifications": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/payout_attempts": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/personal/additional_identity_document/verification_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/personal/additional_identity_document_back/verification_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/personal/details": {
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/me/personal/identity_document/verification_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/personal/identity_document_back/verification_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/personal/stripe_publishable_key": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/profile/payout_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/single_use_listings/create": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/stripe_financial_connections/add_account": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/stripe_financial_connections/ownership": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/stripe_financial_connections/prepare_account": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/transactions": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ]
  },
  "/users/{userId}": {
    "GET": [
      "OAuth2"
    ],
    "PUT": [
      "OAuth2"
    ]
  },
  "/me/transactions/create_and_join": {
    "POST": [
      "OAuth2"
    ]
  },
  "/me/transactions/create_with_guest_user": {
    "POST": [
      "APIKey"
    ]
  },
  "/me/verification_method": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/verification_session": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/verification_session_native": {
    "GET": [
      "OAuth2"
    ]
  },
  "/me/verification_status": {
    "GET": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}": {
    "DELETE": [
      "OAuth2"
    ],
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/create_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/create_transaction_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/disable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/enable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/set_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/multi_use_listings/{listing_id}/set_pricing": {
    "POST": [
      "OAuth2"
    ]
  },
  "/notifications/{notification_id}": {
    "GET": [
      "OAuth2"
    ]
  },
  "/notifications/{notification_id}/mark_as_read": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/batch/transactions": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/charge": {
    "GET": [
      "OAuth2",
      "APIKey"
    ]
  },
  "/p2p/me/multi_use_listings/create": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/me/single_use_listings/create": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/me/transactions": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/me/transactions/create_and_join": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/me/transactions/create_with_guest_user": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}": {
    "DELETE": [
      "OAuth2"
    ],
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/create_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/disable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/enable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/set_deposit_pricing": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/set_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/multi_use_listings/{listingId}/set_skip_remainder": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}": {
    "DELETE": [
      "OAuth2"
    ],
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}/create_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}/disable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}/enable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}/set_deposit_pricing": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/single_use_listings/{listingId}/set_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}": {
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/accept_complaint": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/accept_deposit_with_guest_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/bank_transfer_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/cancel_with_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/cancel_with_description_with_guest_user": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/claim_for_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/complain": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/complain_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/confirm_handover": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/end_complaint_period_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/join_with_guest": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/metadata": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/pay_deposit_with_balance": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/pay_remainder_with_balance": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/remainder_stripe_client_secret": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/set_deposit_payment_method": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transaction_id}/stripe_publishable_key": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/accept_deposit": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/buyer_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/confirm_handover_with_guest_user": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/deposit_stripe_client_secret": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/seller_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/set_price": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions/{transactionId}/skip_remainder": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions_by_claim_secret/{secret}/claim_as_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions_by_claim_secret/{secret}/claim_as_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions_by_join_code/{joinCode}": {
    "GET": [
      "OAuth2"
    ]
  },
  "/p2p/transactions_by_join_code/{joinCode}/join": {
    "POST": [
      "OAuth2"
    ]
  },
  "/p2p/transactions_by_join_code/{joinCode}/reject": {
    "POST": [
      "OAuth2"
    ]
  },
  "/shippo_shipping_rates": {
    "POST": [
      "OAuth2",
      "APIKey"
    ]
  },
  "/single_use_listings/{listing_id}": {
    "DELETE": [
      "OAuth2"
    ],
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/create_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/create_transaction_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/disable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/enable": {
    "POST": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/set_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/single_use_listings/{listing_id}/set_pricing": {
    "POST": [
      "OAuth2"
    ]
  },
  "/supported_carriers": {
    "GET": [
      "OAuth2",
      "APIKey"
    ]
  },
  "/transactions": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ],
    "PUT": [
      "OAuth2"
    ]
  },
  "/transactions-by-join-code/{join_code}/reject": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}": {
    "GET": [
      "OAuth2"
    ],
    "PATCH": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/accept_complaint": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/accept_listing_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/accept_payment": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/accept_payment_with_guest_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/bank_transfer_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/buyer_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/cancel": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/cancel_with_guest_user": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/charge": {
    "GET": [
      "OAuth2",
      "APIKey"
    ]
  },
  "/transactions/{transaction_id}/claim_for_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/claim_for_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/complain_with_description": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/complain_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/confirm_delivery": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/confirm_delivery_with_guest_buyer": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/delivery_point": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/end_complaint_period": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/extend_tracking_deadline": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/generate_shipment_label": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/pay_with_balance": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/pick_up_point": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/reject_listing_transaction": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/seller_details": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/set_payment_method": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shipping_details": {
    "GET": [
      "OAuth2"
    ],
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_address": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_customs_declaration": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_parcel_details": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_shipping_label": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_shipping_rate": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/shippo_shipping_rates": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/stripe_client_secret": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/stripe_publishable_key": {
    "GET": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/submit_order_issue": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/track": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions/{transaction_id}/track_with_guest_seller": {
    "POST": [
      "OAuth2"
    ]
  },
  "/transactions_by_claim_secret/{secret}/claim_as_buyer": {
    "POST": [
      "OAuth2"
    ]
  }
} as const;
